Overhaul tests
rooseveltframework/teddy pull request #650
Opened 2024-01-11 14:58 UTC by awidener3

- Removed karma and replaced with playwright.
- Centralized tests into `testConditions.js`, which can be easily modified for future tests.
- Pulled mocha and playwright out into separate loaders that pull tests from `testConditions.js` - should the need to change testing suites ever occur, these loaders will make it easy to replace without having to rewrite any existing tests.

2024-01-30 19:41 UTC, awidener3 commented on webpack.config.js
> -      libraryExport: 'default',
`libraryTarget` and `libraryExport` are being deprecated soonish - the docs recommend the changes in the diff.

2024-01-31 13:10 UTC, awidener3 commented on test/templates/misc/infiniteIncludeTemplate.html
> +{infinity|s}
this fixes the missing infinity loop problem

2024-03-01 13:49 UTC, kethinov requested changes

2024-03-01 13:49 UTC, kethinov commented on test/tests.js
> +          return time < 1000
```suggestion
          return time < 10000
```

2024-04-09 21:12 UTC, kethinov approved these changes

2024-04-09 21:13 UTC, merged